language: go
go:
- 1.12
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
  global:
  - GCP_PROJECT_ID=cicd-222403
  - GO111MODULE=on
  - CLOUD_FUNCTION_NAME=hermes
  - CLOUD_FUNCTION_REGION=asia-east2
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_b49379da8d30_key -iv $encrypted_b49379da8d30_iv
  -in chotot-deployer.json.enc -out chotot-deployer.json -d
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=chotot-deployer.json
- gcloud config set project "${GCP_PROJECT_ID}"
install: true
before_script:
- cd workers
script:
- go mod vendor && go test
- gcloud functions deploy "${CLOUD_FUNCTION_NAME}" --runtime=go111 --trigger-topic=hermes
  --entry-point=PushNotification --region="${CLOUD_FUNCTION_REGION}"
