language: go

go:
    - 1.11

env:
    global:
    - GCP_PROJECT_ID=cicd-222403
    - GO111MODULE=on
    - CLOUD_FUNCTION_NAME=hermes
    - CLOUD_FUNCTION_REGION=us-east1

before_install:
- openssl aes-256-cbc -K $encrypted_b49379da8d30_key -iv $encrypted_b49379da8d30_iv -in chotot-deployer.json.enc -out chotot-deployer.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=chotot-deployer.json
- gcloud config set project "${GCP_PROJECT_ID}"
- gcloud components install beta

install: true # no-op

script:
- go mod vendor && go test ./workers && \
    gcloud functions deploy "${CLOUD_FUNCTION_NAME}" \
    --runtime=go111 --trigger-bucket=hermes --entry-point=PushNotification
